# Generated by Django 5.1.5 on 2025-02-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MemberModel",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ユーザID(LINEID)",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名前")),
                (
                    "absent_flag",
                    models.IntegerField(default=0, verbose_name="欠席連絡フラグ"),
                ),
                (
                    "groupsep_flag",
                    models.IntegerField(default=0, verbose_name="グループ分けフラグ"),
                ),
            ],
        ),
    ]
