# Generated by Django 4.2 on 2025-07-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "user_id",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ユーザID(LINEID)",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=100, verbose_name="名前"),
                ),
                (
                    "grade_class",
                    models.CharField(
                        choices=[
                            ("GradeClass1", "GradeClass1"),
                            ("GradeClass2", "GradeClass2"),
                            ("GradeClass3", "GradeClass3"),
                        ],
                        default="",
                        max_length=100,
                        verbose_name="学年区分",
                    ),
                ),
                (
                    "absent_flag",
                    models.IntegerField(default=0, verbose_name="欠席連絡フラグ"),
                ),
                (
                    "groupsep_flag",
                    models.IntegerField(default=0, verbose_name="グループ分けフラグ"),
                ),
                (
                    "absent_reason",
                    models.TextField(
                        default="", max_length=2000, verbose_name="欠席理由"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="System",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade_index", models.IntegerField(default=0)),
                (
                    "chief_id",
                    models.CharField(
                        default="", max_length=100, verbose_name="委員長ID"
                    ),
                ),
                (
                    "flag_register",
                    models.CharField(
                        default="NULL", max_length=100, verbose_name="フラグレジスタ"
                    ),
                ),
                (
                    "meeting_DayOfWeek",
                    models.CharField(
                        choices=[
                            ("mon", "月曜日"),
                            ("tue", "火曜日"),
                            ("wed", "水曜日"),
                            ("thu", "木曜日"),
                            ("fri", "金曜日"),
                            ("sat", "土曜日"),
                            ("sun", "日曜日"),
                        ],
                        default="thu",
                        max_length=10,
                        verbose_name="部会の開催翌日の曜日",
                    ),
                ),
                (
                    "auth_info_times",
                    models.IntegerField(default=0, verbose_name="認証情報開示回数"),
                ),
            ],
        ),
    ]
