# Generated by Django 4.2 on 2025-02-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "user_id",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ユーザID(LINEID)",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=100, verbose_name="名前"),
                ),
                (
                    "grade_class",
                    models.CharField(
                        default="", max_length=100, verbose_name="学年区分"
                    ),
                ),
                (
                    "absent_flag",
                    models.IntegerField(default=0, verbose_name="欠席連絡フラグ"),
                ),
                (
                    "groupsep_flag",
                    models.IntegerField(default=0, verbose_name="グループ分けフラグ"),
                ),
                (
                    "absent_reason",
                    models.TextField(
                        default="", max_length=2000, verbose_name="欠席理由"
                    ),
                ),
            ],
        ),
    ]
