# Generated by Django 4.2 on 2025-02-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("line_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="System",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade_index", models.IntegerField(default=0)),
            ],
        ),
    ]
