# Generated by Django 5.1.5 on 2025-02-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("line_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="membermodel",
            name="grade_class",
            field=models.IntegerField(default=0, verbose_name="学年区分"),
        ),
    ]
