# Generated by Django 5.1.5 on 2025-02-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("line_api", "0002_membermodel_grade_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="membermodel",
            name="absent_reason",
            field=models.TextField(
                default="", max_length=2000, verbose_name="欠席理由"
            ),
        ),
    ]
