# Generated by Django 4.2 on 2025-02-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("line_api", "0002_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="system",
            name="chief_id",
            field=models.CharField(default="", max_length=100, verbose_name="委員長ID"),
        ),
        migrations.AddField(
            model_name="system",
            name="flag_register",
            field=models.CharField(
                default="", max_length=100, verbose_name="フラグレジスタ"
            ),
        ),
    ]
