# Generated by Django 5.1.5 on 2025-02-02 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("line_api", "0003_membermodel_absent_reason"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MemberModel",
            new_name="Member",
        ),
    ]
