# Generated by Django 4.2 on 2025-02-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("line_api", "0003_system_chief_id_system_flag_register"),
    ]

    operations = [
        migrations.AlterField(
            model_name="system",
            name="flag_register",
            field=models.CharField(
                default="NULL", max_length=100, verbose_name="フラグレジスタ"
            ),
        ),
    ]
