# Generated by Django 4.2 on 2025-02-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("line_api", "0004_alter_system_flag_register"),
    ]

    operations = [
        migrations.AddField(
            model_name="system",
            name="meeting_DayOfWeek",
            field=models.CharField(
                choices=[
                    ("mon", "月曜日"),
                    ("tue", "火曜日"),
                    ("wed", "水曜日"),
                    ("thu", "木曜日"),
                    ("fri", "金曜日"),
                    ("sat", "土曜日"),
                    ("sun", "日曜日"),
                ],
                default="thu",
                max_length=10,
                verbose_name="部会の開催翌日の曜日",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="grade_class",
            field=models.CharField(
                choices=[
                    ("GradeClass1", "GradeClass1"),
                    ("GradeClass2", "GradeClass2"),
                    ("GradeClass3", "GradeClass3"),
                ],
                default="",
                max_length=100,
                verbose_name="学年区分",
            ),
        ),
    ]
