# Generated by Django 4.2 on 2025-02-02 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("line_api", "0004_rename_membermodel_member"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="id",
            new_name="user_id",
        ),
    ]
