# Generated by Django 4.2 on 2025-07-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("line_api", "0005_system_meeting_dayofweek_alter_member_grade_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="system",
            name="auth_info_times",
            field=models.IntegerField(default=0, verbose_name="認証情報開示回数"),
        ),
    ]
